// Generated by CoffeeScript 1.9.3
var app, cookieParser, express;

express = require('express');

cookieParser = require('cookie-parser');

app = express();

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  console.log(req.headers);
  return next();
});

app.use(cookieParser());

app.use(function(req, res, next) {
  var ref, val, value;
  value = 1;
  if (val = (ref = req.cookies) != null ? ref.value : void 0) {
    value = parseInt(val, 10) || value;
    value += 1;
  }
  res.cookie('value', value, {
    expires: new Date(Date.now() + 900000),
    httpOnly: true
  });
  req.value = value;
  return next();
});

app.get('/', function(req, res, next) {
  return res.send("Hello World! " + req.value);
});

app.listen(3000, function() {
  return console.log('Example app listening on port 3000!');
});

//# sourceMappingURL=index.js.map
